# This is the configuration used to check the rubocop source code.
inherit_from: .rubocop_todo.yml

Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

