# This is the configuration used to check the rubocop source code.
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rails

Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

# Style/BracesAroundHashParameters:
#   Enabled: false

Layout/ParameterAlignment:
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation  

Metrics/MethodLength:
  Max: 40

Metrics/ClassLength:
  Max: 800

Metrics/ModuleLength:
  Max: 400

Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: 2

Metrics/LineLength:
  Max: 150

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
  
Style/SymbolProc:
  Enabled: false
