# This is the configuration used to check the rubocop source code.
inherit_from: .rubocop_todo.yml

Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/AlignParameters:
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: 2

Layout/IndentHash:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Max: 600

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Style/BracesAroundHashParameters:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Next:
  Enabled: false

Style/SymbolProc:
  Enabled: false
