# This is the configuration used to check the rubocop source code.
inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance

Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

# Style/BracesAroundHashParameters:
#   Enabled: false

Layout/ParameterAlignment:
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation  

Metrics/MethodLength:
  Max: 45

Metrics/ClassLength:
  Max: 800

Metrics/ModuleLength:
  Max: 400

Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: 1

Metrics/LineLength:
  Max: 150

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
  
Style/SymbolProc:
  Enabled: false

AllCops:
  SuggestExtensions: false

Layout/SpaceBeforeBrackets:
  Enabled: true

Layout/LineContinuationLeadingSpace:
  Enabled: true

Style/RedundantStringEscape:
  Enabled: true

Performance/Sum:
  Enabled: true

Performance/StringInclude:
  Enabled: true

Performance/StringIdentifierArgument:
  Enabled: true

Performance/RedundantStringChars:
  Enabled: true

Performance/ReverseFirst:
  Enabled: true

Performance/SortReverse:
  Enabled: true

Performance/Squeeze:
  Enabled: true

Performance/ConstantRegexp:
  Enabled: true

Performance/MapCompact:
  Enabled: true

Performance/MethodObjectAsBlock:
  Enabled: true

Performance/RedundantEqualityComparisonBlock:
  Enabled: true

Performance/RedundantSortBlock:
  Enabled: true

Performance/RedundantSplitRegexpArgument:
  Enabled: true

Style/RedundantSelfAssignmentBranch:
  Enabled: true

Style/SelectByRegexp:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/SwapValues:
  Enabled: true

Performance/AncestorsInclude:
  Enabled: true

Performance/BigDecimalWithNumericArgument:
  Enabled: true

Performance/BlockGivenWithExplicitBlock:
  Enabled: true

Performance/CollectionLiteralInLoop:
  Enabled: true

Performance/ConcurrentMonotonicTime:
  Enabled: true
Style/NumberedParametersLimit: # new in 1.22
  Enabled: true
Style/ObjectThen: # new in 1.28
  Enabled: true
Style/OpenStructUse: # new in 1.23
  Enabled: true
Style/OperatorMethodCall: # new in 1.37
  Enabled: true
Style/QuotedSymbols: # new in 1.16
  Enabled: true
Style/RedundantArgument: # new in 1.4
  Enabled: true
Style/RedundantConstantBase: # new in 1.40
  Enabled: true
Style/RedundantDoubleSplatHashBraces: # new in 1.41
  Enabled: true
Style/RedundantEach: # new in 1.38
  Enabled: true
Style/RedundantHeredocDelimiterQuotes: # new in 1.45
  Enabled: true
Style/RedundantInitialize: # new in 1.27
  Enabled: true