language: ruby
  # 2020-08-04: caching significantly reduces build time in travis,
  # but we're currently having issues with obtaining correct cached rvm
  # cache:
  #   bundler: true
  #   directories:
  #   - "/home/travis/.rvm/"
rvm:
- 2.5.7
before_install:
  # 2019-10-16: added to fix errors when upgrading rails env
  # 2020-08-04: removed to fix errors with travis deployment -- 
  # looks like travis internal rvm handling has changed
  # - rvm use 2.5.7 --install --binary --fuzzy
- gem --version
- gem install bundler -v '< 2'  # helps with compatibility issues when upgrading to rails 5
- bundle config --global github.https true
before_script:
# - bundle exec rubocop #for testing
services:
- postgresql
script:
- bundle install
- psql -c "CREATE DATABASE mln_test;" -U postgres

# For testing commeting below code
# recreate test database from db/schema.rb
# - bundle exec rake db:schema:load RAILS_ENV=test
# helps travis update its test db.  seems the schema load below doesn't always do it.
# - bundle exec rake db:migrate RAILS_ENV=test
# - bundle exec rake db:test:prepare  # NOTE: might need this later.
# - bundle exec rake combined_tests:test
node_js:
- '14.16.1'
script: npm test
install:
- npm install

deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-dev-1002
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: my-library-nyc-app-dev-1002
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: reactonrails-development # for testing
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-qa25
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-qa
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-production
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: master
env:
  global:
    secure: VmSPZTuC7ZMDSloA+sxYBa5MP2rchrlSVLvMU7yuEv9HI8tw4FxzUmex1IBUG976zMdsfjerjjGiXaJURC2xQqWUqoFEG3wsvEKEKo9ydMAaWDN8fvlX3aEkKoG7YoBmUozsOEn+SbGiEFg8ApdB9OwDoZ+tVhNKs8TPD8KfJX3ho7ER2FpvfNPtb3l+ZydYWWyHx/jw0aW4DVrRxHFY6Z/ELyNjaLte6ikh9kRjwNQ/Krmss8aU+k5PrFi4U1JocQEgbKXhR+Vej2ASjpb9KIS/c/EWpvs8Z4uA3baYhrE7HsPLKtLnBelSsfqCRH7UOP+ZOWrgZOtvRQFjqCXoLzmKwBrlY9sNAYaPbTeEIUHpOUJgnHqWM2d0PuXqOV3aVxL1HiXDOqdcT7e2lgvBNgLRmdkXdTcYgZ5pTBF4W24n29sxpfzmKOalYVowiv2noqdeNAEbOWjd6Nj+UfYtwii6QRLRAGVx8qm38msoh1IsHNdjHIqYaAd4UYIU3nvN8veKUf42bUcrFafKG0TeMFs76ZUPBJQdlFgtBqDnEtRxhnhfc8NQxgbo1e+cdZapCMa579LDn+mNTuAiVLGxzUTssdCxvOQONZr/L7YKUl2RfJRbm1Hwa4aRUKHsb4tWTRbcqMXE8fnmA6nNjklHHzW5vCmJOF1enuGoLnfqQt8=