language: ruby
#cache:
#  bundler: true
#  directories:
#  - "/home/travis/.rvm/"
rvm:
- 2.5.7
before_install:
- rvm use 2.5.7 --install --binary --fuzzy  # 2019-10-16: added to fix errors when upgrading rails env
- gem --version
- gem install bundler -v '< 2'  # 2019-10-16: added to fix errors when upgrading rails env
- bundle config --global github.https true  # 2019-10-16: added to fix errors when upgrading rails env
before_script:
- bundle exec rubocop
services:
- postgresql
script:
- bundle install
- psql -c "CREATE DATABASE mln_test;" -U postgres
# - bundle exec rake db:migrate RAILS_ENV=test # 2019-10-16: added to fix errors when upgrading rails env
# - bundle exec rake db:migrate
# recreate test database from db/schema.rb
- bundle exec rake db:schema:load
# - bundle exec rake db:test:prepare  # NOTE: might need this later.
#- bundle exec rake combined_tests:test
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-dev-1002
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: my-library-nyc-app-dev-1002
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: development
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-qa25
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-qa
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-production25
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-production25
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: master
env:
  global:
  - secure: OoSnnbYpSGc0nVNPM7GKdx6qgWQGqQdmRP7oOP+OKx3eUfc7CgJPtV515lwKYXtoQ67UqHt/Nc2lX8ofjARhuCBHC2j7CtmJLcHjxB+GBTTVmw8xOyaS1Q17S+tRJc0KHHtTAYrOAn/nvmpJt8fvnfWzx30mLhpApo4dUfyaLYxkz4gP6/qLyyGuqIlNse5x5EQR1Mes21ym8neiZsiZkQocM5Oecq2jRZiBJkzvuw2wPUxlshL/be7uS4YW6HEFOzfuJmtI8J5ZskbAN0hqcmF9WeaPRqSIgJ5Lc/PcpiFbtNVHr2GYGr8qNi+X5JjLkEjAK38a3zJ1AhNbMQZj7G8F8EGHFKbBuiJUIWvyaJdoyRnfLVTXBSTxfSt2k3bVMVgy76j0OyvQZN0wpW2fl6W8mVyCxUJIpYJtJO2JYYqKDSSr6x34FHjdGUeURwFwjtgnhA6zc5DOq7KcQfFKuwZ0QUeEUYsqzLpifr2tjjgnhtKQuwXmerJJR6YYsizkvs9zIgomVLdtnnWQeQQmRNsoH7X0mG+8iQQb5fRQ0q2z85gc+5rmxjj94CTiGydyCu8E7f2Dp+zUV1g+Ilw7YSbqVpDTyc/I0vdygWyUYIC9PeUJkYBss1giS3+1Oq2saFrbhAktyB2ovNyH3EY4Zp8Sq7SmDeyjRx9xs5YsODg=
  - secure: oJmVcNLvop6YDExulyr23CkVhcaKL4LqED5ywSXFVdGqG9CT5uXznStulqkVLPLiL9H4PpPHfrALvC2e7W0eEqPnsBrfiN3mm+iR/8MBkz6BRftfirceS/uthkkcEIrVpOLSC/hVbrdZFG3/Fn8ILtJilhwuLWTvUHG3O1iRXf5kbrcVWkEvsj8Crsm5ceNyc0n/oA6S/gWgU86nT3SmVJj0xfdai1r+lOfHHC6GORPtIfho8ZlVDjvPQKMiJb6pogUqvROocXaA0O0H+4QZlGfZN9g2YWYNloKbm4ynCsBaQlkbBY/0zkYGGpzb8geMCo401JBDJLkkxSdL7QE7g0+GnxoSjoS4tk9jwZnhKlj5N7ZWx6HeAF6ety6YAJIGaMdTNpD+mlJa60ypAn+kZwpP9mGuA66etrotJUkMFhlB9eEPVAvkKS/bzajvg0M0BDFO28W3XX/2Z8JwOBRQJcGyNUIRGa82hqySDmSCbh28kNjTR8nwpnfMXm29y4lIZdqY6fhgCuc4aetqEEAGAsaNA0SAQaf8i30Bsq7t0wJ1wfWvre/3xK8FpywuEXuwLOOrbJZ/S/yMZSbbr9ZhFRL9pmgC4HNWPj7W1Mu9MCJ5SuXGg/1z6jklYS1UJrAFqgUiVaLxYv+7/VBlhN5XYwCmg+IN+9vtR4PZFvnPyCI=
  - secure: JykdJlLDlFMcs7J9CPoH0P8eXYlF2/Cr6+y8G83SnBZga/iz4pvPcBK0CNT0O0WiZ+c+23NDnX2xkfRVchmJ9yGUzjJe9ENtf2UYeNW1IccpuSrtxzjgoxcoE0vhMckyjnNuXKGQX6W7sw1DqPLP/6HNTkI8xBeVnKKwt/UFnDZLJthq2xbDx0dgsQm5Mi+6ZA9fFIeLaMcriF9YliPSCMygWUsW2r1Eb/DkLUZ48V/qYD11YeTeUC8o439vAhhpix+0QEbdfG0NIl4qm1lFPOeX66jnP4XKI3JV0brR1ep420vpNVP7oVGKdBHk0DSVi90JlfLOxpbYcxMIg4xtIKVf77JVLmulx4VapqohnlIGsfxiU2iO/7d2iOAN27h+MgQeklMOV3v7LlR0rd0ciRWKV7k307I2yrVfbQAbYE7MfRXxNWDuhwkUIzUV7LZZTKSvOMQEJP99YR5a4Pjjdlda9QhRHCMLnYeyPK3k5FmOGxNNfadgv/AemFCTlnYnF0ma9DGp/FN04mHhLRTJVHQ4ssBuKFUqCFvsVY0NVjBZqCVetd7l3odG3dXDe44yAWUIUCvtPwq5qPcSmO1Up4ssaQzjdFPEFVnRpMK5ZUoKixCFPzfK+Sgdd/RgyIQjS2ypedKyJs0hFtz20D5haJ6Jugi/rstoUeHFvZ7BzN8=
