language: ruby
rvm:
- 2.5.7
before_install:
- gem --version
- gem install bundler -v '< 2'
- bundle config --global github.https true
before_script:
- bundle exec rubocop
services:
- postgresql
script:
- bundle install
- psql -c "CREATE DATABASE mln_test;" -U postgres
- bundle exec rake db:schema:load RAILS_ENV=test
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rake combined_tests:test
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id:
    secure: 7Qp2i0ce0h67Rsk9/2irUAJttcqzmJf8chrZiXq1a+WWWYuKpYd7STqcJz2wRV/WD044jAWAJt2117vb+0zmMamOGmyVMnd3gwILrdBjmllz2aH6Z/GKUsIXYH7GQ+zjEPICaRdsVSkEgweDtkA7fsIij8HAQ/YfXsdGq03V6903EDBJ327qsxs8JIWUx6tM4owRgo5swrzyPH+KQ7oUiWOizLF5Op/FeIDeQkwhgs5sQGejkAU01ey4H2wDw3RZbKgyCZK/PUK++kkesia8RkYIi7C0u+jBDkqjJylaBeMhtMVwl2PC0aMGuF0pBrmR71x+zNVxhhekskaJN9DkMOoycB4/t8yTFPWSuU+vKcqeut+jgV+XxNb+cmw3kmRTlR/s73hCcIga5GTmVoWB6/fN0ttYipTU+BiCDgIOdyd3KPC451z5+PzDTaWOgHN2fw1UGRxHXYp4DsnpWyxpRLc3U6hebwSUn8LB0zx6/AI+CODD0SzDzTsdcWdK3sj2ZhLxioEaAydLI2pLsf4dOIG/xPBgPqr4mQzcU6cX2e2gT5UrcRJnE1i+pqKkpKpfxAnS0CCiBxY/fhFWIJLodZjDH6x5fztgez9B5VQk/mhhgiiRv15PV0ZOOibtqao7vAp3ZkfJeVkqLyDG4bQfEnWgW9tAYkY+mqse7g84i8E=
  secret_access_key:
    secure: kHUJAlXQa7tDgVguVZndX0nC+xJ7l0gvLeKo4zHalwC1Sy9Z9is0sTSigEzFo4JdVfh8tSBjOxKoeFs1ZU98vgJPGunVMeYxjj5pszxhVGL9PBk0ec4CVdLRDr7wNkhvAnUhNbiSCKOufRcN1NsCXKe3DINyYel0QmJSyuVyt9Y4pWtIOD4hTn1R3N4E5+GZJ7xkOLGEKVk9a479f+TCZG1fTg4HKZSE6ZhpGAv8D6+55POmmZZ+CkUat8ukACY+pYz5444bfZRP662HmNsEnUudxSQtLR4H9/mzkNXWDZuxu6y3j8fSZSIRyJsqIzB9carRLcViqglvJlZrs2Sb3r8ta31VgN6ugpn+Oujj8TF+OsvUMbsHo66GsyB1Ly/drtSboOcdAlTn2Qcae+7hdY2zqJjxPQdgL9iHacM6HEaGNDGHfDOaNwCE0JeLLcCNsL/R6feDIKjokus+M/fczzk0yMcO0v/kqHjKtgJZKmGPeKas8kwNtsTMR6f/ziFiHHbaM0MRgIRYNyUJTfbmhfJL/Ll3IRVNiCPVJmwPLXtE0mzvo6tkfMNXFutkGs195sGpDId9BjuzcoU42y/dupMl5iTm+a0OSJ0YePa4CbTe1grIJQrtrpy6RRjXoS4UYg7HOHpP1OQfv1IxeNzm90qtFJ0Z0kHyOy3p+YO18x8=
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-dev-1002
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: my-library-nyc-app-dev-1002
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: development
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id:
    secure: FOCoAtIpdP8eBQsqfnnHKXdQhen7lNzOO1INTzKLjBGuSGlfcgKseWlY3Y7hQH4RUnUtOcUhbTpDTuKFy2KHDb8OvNFKD1OuDR2GgjlY3YAeOlRYGGdzqg274U06Z1G3LoexKNtlks0pb3RL1bgudIyPZ5jJE001P3RnxY4wTvC3rU1YzEf0hvxUR5Ow6fhqa3xw5QW6t3bUOpGeLwXa8pthxZpWwd5mKJ2ehhgznVqbVg2Bu8uX56DDqLV2xupaf8yert8karWQSEd7Xf9WzjO7vuH+9SZa6MFdZZ4ofF3H+xAcpfkcSWYScNmPDBqW/lt1xBTMBSCX0XpgFxPBT8BCQc5y9fxQUeXmJMwEP0H1Lte6Z7KKKYSXDY716u7Mu/DtgcsGIzkCqdHeHXUgxMYMg1uagK4MIuAOywMXMCfroTTeyniAOGYWKPzsUzQAmxMmn8Xr6tonnsG5lwo+zQbyFoAw6OMZCxdarGOg+pzoDSvvBhdSH9vJb8z5wqlVrkAa92vq60CEyWeCxW2BPANnZptL8/Cvc/L2SJBjmFtXrKYTG5u2ILuqyN6rOCcjfs66xIVzg+qe9QBb9qKFP4vzEelfwYe8RK3NPimjpO5SpWFXJ1I+murDghqL/g1O3AGBA93HCs0dzPcOPAcIpZqrt1zlRZ8QTrRSr2YgaXg=
  secret_access_key:
    secure: tL2bf5kopX8yCddyyHcrEbUL/TlyhwqWmaNHFiV26lgIZrZ/WW4dIn2DJaKTsYXpMUhAsBzXZkRD31/eiI9jYcIbuV9PaAjWvULR/TIM0PoHQokprkRKcxIZr4N4d8wzqb2N7VGdq/9Uo2jsziFSye26eTRDz0qolZZHs8rbZ3tMVviw/Usk7zbRQHPjzCO9C4Kvl1HHkkKmJMf1AADsYtB1N8vsMYDgDktdTswipQf35k//Lxrvg2BshueBw0cX7/aqV6Mf0OUEeyXGAVqYnW1VnVo2i15d3jmzbsbpTs6Faz2c62+SSqUe4v6pBqiEsta9iyEcqXyuIuqgG7bpJ0Km4nHmB6sKSSw+MkjwB6g2SYm97Gh/TsgAR9CtbONclDIpTWQYYgpYbChCsxNrujzDxf8wD3sq5mzxlN4oCrCg0uwFZ/jDdnVtTBjd6DUQDC9OcTpXkNQGcy/Z72S7jG7leFCR84CBRDD2jhnpgMcK+PLCL5x1knchqvSJmcLF0K6ENAxHMJkv+XeBUyUWNJ3sBdZy6m45enMVBzfUrVUHYj/+iogjXnA3Mgexaj+O26YuFIredPnv6M6larbUOUtA+dYAT7nwx5rHDkRR6aWf5/dhVTrNiRp312P218rQ09L1alsVbHzstFFOc3a8wmEUGDdLlEvM8IgG97inOGE=
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-qa25
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-qa
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-production
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: master
env:
  global:
  - secure: faZVumCAp4/e9vGo9whJZ1fZGFQ2qnfUxt4iQoMbXPlcBb2rVGia1hEiwrKpuJ/1mms7Rp7qhoZSR6rQQwjnGjQJ+cclAJo8X3yBpF33y7u/BwEQpS4XXxa1SNiIitYGIJ1bWxALQMkUgOoeI2D8LW7Pi1RKyW/CAWGD84bZocGT1S8VHX/zWl1JxtjZPGL2HmRuWXerIcQABA2xHaB9DZhEUNmF0jgwRdevDZQxJvAehpaB0I/meidFzd8k07O2DhgpCEHcf9SQzWf8MgGV9znnNRBjEESeZyKe8kSnSFk200mpENG9xAiJg/k88GaGTO6Biegj2RA5BFyOwpjxCn+E4eAN8AATMTy/rvoSssgBNAr0uqDmjkNcU6ffNuqPcbQEyhD1sb5XVPh0K2GcQ3yRzHqiVJpHreq5ESEtMLygUdPxHGMgYFpJBZ+udUGP6swUb4CDpEqVn/vmme8CtjKTSIsDIf3iS1nGxzd4TDtD8shqMOjdCgcz4rFuAr5Z9EPjTxbBUsPFkzOis60tuGPj9I1nyZ9+VDJhkJOzFhcS1LTXjRNTKfVNS1O7OVEIumu10eZLKOqgVp+SAGp+0wvHcRkX+74NvevTGUG3kwO+PQEm1YLdo5q5mcqmWbxggIwrTAHu/kjGEMLWUfTHbUjF+ZR7pptdCGUfLBQAJyM=
  - secure: bSAghtmg2DxfuS3vyCbD+bNQP3tyqc1VwooV5faInNx8DqbIdop81Z+J4m025F/AIyMrjnogm7boErW3JqbSfFYXHfGgedH9hYu2L5RLa2cn7QYD+KTDJaYIo9Z2GDExRtFOHsNJAf+IJ9gNGoRCRdNUyDAcKjJt4D+SIqB1PLMT9znc0wSPawIS1GrieZfj7zkid4hBH+xrRiE8I943+mQHvNCvkirKF/h7pEsMdcsGYATJIpKrT865k9oubLZvuzkgjOa3yMN02nxtnzMhHUiQpHgH5kXpvSiVAvbi84Ou9GEJY2sWdSwr0bezTICGjZagSPdsGuNC7oDYcJfwdLXk/CkF9o9VnXxn1KCki/5BSMK9LgrZ7epcMNEnZq8mpTZsCefc8jhF4V7Vd1Xw2b70Ei0Clfdn5cRfwcbVc9ytVLAzKUtFf3RJ6LlBJll0cBna3szEvrEQjiI3PdXwjtQLQOnj9tzV1J8RrmukKAY2W/ipG/44n9R7bhOx1MW6EgQFgKoYdGzdTP2CFLekEqNm4aibXCf4JBpW6QxVfp2sFfGduZVC8UUUJfdL6shIOrf6uQKhWehA90ZPBzlwO8j/A/DS7ISCsWRFKmt7itBWO+m86go/e2nz+mqs4a0r7WtXOSetKrJLChdc6kEKFd95towPIhmFdzxhUV+g7hA=
  - secure: mevQbvPCNL9bWtBC9F1T3ky0FXr7q1DOIcmngUJDyE0Onm2OEMj/LgF3ZpO9YPTL2OVT9B2yCfvfs2Mg3QKH5if5FIEoTwSUwU28cQmqgfwmdVvcUfGSxrhGZIxbKML1xV1U0HLnVrJMdusVHO1F8PhmXJ/vKAr0cDGZqcKx7sY5r7dG549McZUfbPmaqHampvGR/wFb+DacJxJ0xoNdLlvt/QKQPXfZIjFOKbA2hcqDc58XVJbd2xg6Xqhh7k5wmDDNVosod6qhL7OpXpQWZqVzVTLIZnwQk12caXd5RcvgdElToPAGikXgYktxmYEG3pUHm5Z53A43dvQUlIZt0Xp89zNZA7fQQ0Fh1MGFLpPRg2fln3h554c7RnKp2ZdO+herWT3wTUm2+C8xHKzM+3HOJEW1lEswT3uK9+qwlQ+fqYlH4ElYFD9KSmUpFHUksfE1eAJKhNbtJQTz04tOON2mtyxE2s7Q8kP7TEtXbjOnEg9fmpVt353WJCG13obS5AMqQX11oS2KSsWokJILbIcevKZPtnEeNYdpX+JfTGEH4lgKxsiSLBe3fyNw1ZXxwBaJXZyLFhAOrxQkBy7U/EQQiSt5nL90iRI/tC9teaiTi9hjvz9Ai9oCYWMAd/H9C3wztZqEv1l+pSOHWZ7RmsU80wjzXeSJOhFP9Xu4n+Q=