language: ruby
  # 2020-08-04: caching significantly reduces build time in travis,
  # but we're currently having issues with obtaining correct cached rvm
  # cache:
  #   bundler: true
  #   directories:
  #   - "/home/travis/.rvm/"
rvm:
- 2.5.7
before_install:
  # 2019-10-16: added to fix errors when upgrading rails env
  # 2020-08-04: removed to fix errors with travis deployment -- 
  # looks like travis internal rvm handling has changed
  # - rvm use 2.5.7 --install --binary --fuzzy
- gem --version
- gem install bundler -v '< 2'  # helps with compatibility issues when upgrading to rails 5
- bundle config --global github.https true
before_script:
- bundle exec rubocop
services:
- postgresql
script:
- bundle install
- psql -c "CREATE DATABASE mln_test;" -U postgres
# recreate test database from db/schema.rb
- bundle exec rake db:schema:load RAILS_ENV=test
# helps travis update its test db.  seems the schema load below doesn't always do it.
- bundle exec rake db:migrate RAILS_ENV=test
# - bundle exec rake db:test:prepare  # NOTE: might need this later.
# - bundle exec rake combined_tests:test
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$access-key-id"
  secret_access_key: "$access-secret-key"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-dev-1002
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: my-library-nyc-app-dev-1002
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: development
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-qa25
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-qa
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-production
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: master
env:
  global:
  - secure: GGTAzGYXTqTjFUDUIcZm33/VTiSt+XduKsV6JXJYtGYJTpgbooG3ahTCSHUtCiLXPrKYukbByvuxkdPRycJwymYl3/3uN8WqyBtjMla/7Nbso4A9O1kNJX/XK4OfmUZ1jU662FQKMtxCTHKoqXhvu7xtZ3m3aZxb012kqLTxQAGdCH5nBcMGQpC6njBB4bAPoOqlkMseVv7+oY60Z4GrWcoLdOZXkP3h+tNJPiCDSTTvddXZglCQ88S30nJXpKHRlWNKsMMWHzgPK4Ek8UqHA1l/vSrCBIig+x5KljxmArgAGctr6A3fmZarDnvVJnkO5mg0/eyGw7PzhYgyYaT6HUe8woU5tmSJL85chKyJqm5hhGm/WPwthxPA8QgL9S/v5u4Pvl+d518NSv4imm1gkFpst+3Pe1xrjD6vMJgrCR3IU8ZMMVdda6q8LuPLCVKXJUyw83uD7WlqgkYgM/I6DQEUfbxCJI0SjIp+aoexwf0Im13it5gkC3+ziOp63n4oYoiPgkEYdILEakj8D3dY0urGYCsuhEjsT43VOY8iagwONXZhmdG4bq0VtdSKTkAoZ+FGGRI61wwfHoM3JW86/2iBiYNqeL/UYlYKpzl3dylODh6kXhRxBz7HjX9lKwPzYOY5w475Ol7dVpFkQbBb/Bg8NMOJAIDfrfqSKtGZqAw=
  - secure: sadY5gCquWcKHFEA6Ud7eFuMS5bXg82z0roJBFkT1pGKKnsYVvK/AQSAW5cgeKs0pu3MbTUvQszfrZBYcZWwUtSO5pwSKwWErjTbHdORUVxUBKtIKp5Cl9AJRX7wnxsCdEmBqFzPZ29/VpWGD2Me0zKnmRbjn+UDTKju7Ds01P/qV2QM5deQJeG4ImGnTpLS0UK7K/GuPrJDTiE6yJsGpKQOjTQBRHF3Ghi9fhQSCo04gPUKud1VUvZs63bIF9eDSQHRD4dYNCKbPi3cfNYlYmZ/oOtQRtjCJcOn8a8QDl3AdGsTI/vab/gARvOj+9rD79OWgUGUpaPBsOwJjpbLWYqy//57SXHFk23EkiTP0GRMbiFsr6i5chvTnkuTmhH/TRhidH3Ie18ni1uBRNlSwTPPrnCkJI6xTuMFBpDK0fxbI9FXFbUY8qFTtQCLwXD5bRHr5GCJ3HPXmXurYHv/TSDFZDT6lAYsGMSH9Z43GM2ys6BRjnGDA7od8Yb+p5qeVoXfSmTs6+Bzm3UTer7F26BWvxRkYGXXCLJaglDEyG/X4WaDvrDtKEqAbfqO4gEqA28xZd+nlezTUhSIUOtSFjIxD3UXwJA47JJCDpD2tnfxO5QSdwsuYBwhfrV1tZU/JBedrTsnNCWrJtJM4sfTZQIBpwgngfrfTHkfuVXXJUM=
  - secure: ND/0dzkU0e34s//NQowU+FFGl+yPBh4vXf0OitUaPoLDhzLpZhql/+kc7CqVPXXDx9GDC9vd/Ze6aaOFn1Zilc5YA2dHg0zWRfbD8WcMuDVvyR9TibOI9dl9nZsquu2rGpYrI5tqPv9tOQrkTVBmjLql0Bsk+LIc4Lv5oVd/qnqcGkIh7ackRzb6P0ZqH9OzgsA0Z447RGj6IkKIVGb0un1qvceaJ53XGdz4jZOuNuKNLtzDMBm44ZNTjgZ73KQESm7XV6UybXEqcyo9r+nKBx17dBUilgb3pvdVHC3W3GOri8I2EdG1JFSJt1xGoJho5XhY+MLoA++i9+ZqPiyB54daJRgUO31sPrjaB3X6qok606D8AO91/EY8l9C5vif2pqUDvxB76ycVHYn1YNxcIobdF9wxv5PgfghI8K6apeYXKWYLjNKNWOW95V80qAI1uG7t6qndDL29088T4VCuKobzMYuR30TTNEsaLmCrJ6MrnC++kBuA0H7xHcpYugtBC0e5Qnf1RO3/TA6hrsO9eRW1WKIQOIcuEUrtLTT8aw0ZQ/ji/g515URBaOoOG4sLAB2v54Fs6mtv95J1i8PBVGrBTVJpzmIejMlsW8v7v5KZ3EndHuiCWFoXl6S4wb50eJMg2zeT4RG5Ei4IFjn60wSJZBIiKTUnJj6jVFsKNto=