language: ruby
  # 2020-08-04: caching significantly reduces build time in travis,
  # but we're currently having issues with obtaining correct cached rvm
  # cache:
  #   bundler: true
  #   directories:
  #   - "/home/travis/.rvm/"
rvm:
- 2.5.7
before_install:
  # 2019-10-16: added to fix errors when upgrading rails env
  # 2020-08-04: removed to fix errors with travis deployment -- 
  # looks like travis internal rvm handling has changed
  # - rvm use 2.5.7 --install --binary --fuzzy
- gem --version
- gem install bundler -v '< 2'  # helps with compatibility issues when upgrading to rails 5
- bundle config --global github.https true
before_script:
- bundle exec rubocop
services:
- postgresql
script:
- bundle install
- psql -c "CREATE DATABASE mln_test;" -U postgres
# recreate test database from db/schema.rb
- bundle exec rake db:schema:load RAILS_ENV=test
# helps travis update its test db.  seems the schema load below doesn't always do it.
- bundle exec rake db:migrate RAILS_ENV=test
# - bundle exec rake db:test:prepare  # NOTE: might need this later.
# - bundle exec rake combined_tests:test
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-dev-1002
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: my-library-nyc-app-dev-1002
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: development
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-qa25
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-qa
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-production
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: master
env:
  global:
  - secure: dkzpmXtbWUCShyT/5jXP0R1xb4Gd4VU8rP9IFecZctGMMgPk/evEhNmkYiHc64Atrr8o/S54pKHwFvFfcGYoZokFDgJSfNovJEHquZmv4Fsm4PrgKB2Dt/VVSYMgmRlrj0Vj86lytfou9AfG/QemehkrLmL1UTXKadgIaCNeqLjvo616CNhKcs/IWlGkxEBw+GMrPsXwdWgABJCnQbvum3hRhUN+0SYtA6sywmnRjX72OArbtJfB+jV9j5RTMEqBWSn85OWWWbMsa9rGVQRRmKLrwO5dEd9PFO8YzJrDzloMCWwJUkwKj7rWJxTMPanSXznzlMrl39DUCWNT5BFbtcfB3D5IHoIOm6NbVz7/UrQgGnTtzJaNUTuCTgfxAUl/BdiM+SPG0+kZMJMtfSHnxGyTCHY7e5PJHsApts67+SQ82Dk+poDvigXsG5k4WuzgcNI9HPwOE5ArIUYQEnFkMEWcgFGeP+14irGqf67Q4jU0fRixWrad/1NrNSrtxfzyKi8e11z+7K3sNj+6gisouymGWzTrsuUH3o7HzYCmcIUi7S7kRuYpZitECJ8LxfQmXlTQT0+baOSJ9RdCce86TUaXFJ3hOcbv4DCCp2l/Ol+IU2cu+EKJShHKV2pSNR0/kOKjEwRFGehEBrV4oWfZ2xpevkTqtCFzvv2hqqzG4bg=
  - secure: 76n4LXjIdoMiLEcIllaNe5NpWuglFIxlco7O2muF5urclv8zUK8L2pc8ynyGWYrhfvlHcv8YB7CWJCEiyDxTXJM76PFbejdNLn8SLWwo0QKhv3anzLaUuSTsjDLB5/hikbBgz/bxRRH9p3TKXadW+a9+ZOgsNGqL4EZMHXWRfKFVJk7Hsogj9okiz1HYAHekmwfWZEKGqcroZ0gqXjyIC2K12KBpodji4ArqmnPlOC8aqGyz0o0pNqpNJ6fHQfLQN7mAbMmDJf1LM7Q72amJKparWtLfBwH/I196xzRCR1NCNjvDb6MWvcUWEeOvirR3YdV6e7bRrSnZks72Y7JVsM3KxuV3hOFVGBuHAHim/8SR9jkPkYscgTVlPnSAGKG08DvxW59EnnOpcsSHvCXC6diEBIhorymCcFHpzGUH1FFMmvzOWZ3p3ZaJRFOjxKf/J/Yit5eKMkotOHpk9nHmojYy6Xei+AOFb3IxWK7M5Sl9RaomB0g6FgOkjTw74BfJcznMa9P8YaJ7QNyB2Hh18obN0A4e8cKmHIsu/jaSs23WZ7XrrazW8oQwFHOOx5t3X+TFb0NXFXNCjHZUvxcPc8eg9oY6HTFYfhRHYdICrMKagP1yOgF+MD7iIm77m1AwDivHWfDI4uvNPaOFLIlSembQaczc9FTOYjBkgBDnDx0=
  - secure: nq2WWmphGGAMPPrW/oRmVP4J1JtfLiVlEP+6nB6Q0EJ2U3dPfSvEmkl9gkkWHn+z90dD1Va08tysdJpNGw3T9DJR9DbNGks/SFWV+4hqR7ITDQ4Adtl1R2H8dVubiK6gWNSCvfYmgy9fkM+FUnbD+2G5tyw47TPt3K5VjrA+32TL0z/XVcBLvn1+ANuxRw2b4OoZaI9EdCc1bvwDtgF2geDkBHJtfTqEOZ48VV3PwcPsjTO37XOcUHrUg5MrEKIpWCJDBMQjZodtj1vTw/mFwA/UStURXAY4MIIQvHOHKZdrMyGXWgIc0N79OjbTbhW+lPjr8yBdnqgWQHSOryOpVDNZUMdL9CjyNYktFfSQsjAuVt2uVQSr8RmPj65BMTf4EE+ZjNFsxm+qqYAtz3g2/7Kse4R2pKymP6r0XHmRtg/0Cs6SLVAOmgJRaL8W9fcwM/uUPlbttbdnI6yv1jePPV3XynYZqzg9C931oDqaE3XdLA2ypH+8jsNhtCPuOch4l4yKywc3juHO14nFHrzewy6Qd56FLQ570P2piH99SaPSp/eZju/VG/wDqht6AGUxcc+3Lpadgf86pOJEy53dK+wEsV72lH7T+qkYpcZOL0LnUZ2FPEe0IJLTFJzsH4wajZG2Eiy5X6FCk6YeN9AOg2JG4wcmC8g9cePj8YfkA8g=
