language: ruby
  # 2020-08-04: caching significantly reduces build time in travis,
  # but we're currently having issues with obtaining correct cached rvm
  # cache:
  #   bundler: true
  #   directories:
  #   - "/home/travis/.rvm/"
rvm:
- 2.5.7
before_install:
  # 2019-10-16: added to fix errors when upgrading rails env
  # 2020-08-04: removed to fix errors with travis deployment -- 
  # looks like travis internal rvm handling has changed
  # - rvm use 2.5.7 --install --binary --fuzzy
- gem --version
- gem install bundler -v '< 2'  # helps with compatibility issues when upgrading to rails 5
- bundle config --global github.https true
before_script:
- bundle exec rubocop
services:
- postgresql
script:
- bundle install
- psql -c "CREATE DATABASE mln_test;" -U postgres
# recreate test database from db/schema.rb
- bundle exec rake db:schema:load RAILS_ENV=test
# helps travis update its test db.  seems the schema load below doesn't always do it.
- bundle exec rake db:migrate RAILS_ENV=test
# - bundle exec rake db:test:prepare  # NOTE: might need this later.
- bundle exec rake combined_tests:test
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-dev-1002
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: my-library-nyc-app-dev-1002
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: development
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-qa25
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-qa
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-production
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: master
env:
  global:
  - secure: hZjB4XCBb2LNIPi7dexFgZlkG535oLGvHyJK+06Siky4qE9HcCbqCjtOVVVQbeEQ/ZyQw0wUoII4pzbAbsjziazdWBMbCCJMHQowVaKUTZ0qBitIk2S93cxTzMZ0tAImP5z7M4Sm3lnBVl23PfErqgOv1idXl2gaz5PCqboszLV8nw5/pt1G11XCHhx6CLi6hOwJTrjN4ly0j9XYDWI0uIrHzm34OmuEyiypbXSR4gfomPI9qO+qMHWsa1Rlre3a2OAvCqjxowdbKplXcSk9lUssPtqjTDCongvzjUvBjwIL1yaxJBzAjEdrQ1gf8sOxqkOXZnvosjOMJGt6CjJV0Fqgeifyon2JDsQi8B2gD58TRiLufL88KaAe7RtmxAVjeQizuSXSnsS0QR7Bpvlxj7dEDG6ynm4SBmP3LM4JyJGe/fctQ+VkbqXcftuZJtUwCBXWrXFjqbjQ2u9OPrhMh9JKrMhMlAZULZhXZgLyptvXziQLoOe0+FSFO3ct09eSiSpXNaogpgXA60A3vaw1xVJlHCz8VF6tlGY8Eh/qDzLmz9DmDjeLUaC3CySp8TLG4Y9Sbcty5GCZ9EjQmcSJtdzPoKtaEdRAqptXTAoQxw977k3VbAIgv7nbfVaEyYwCvJ3pUs37SMq/TChdaRi45pZqGyzX5qLeDhA6pbrCZdk=
  - secure: VIJ6o0126cZSYgPjTmmb+QIRM0M5hDx0JM6IWw5PY7NckDOSdMozN4o6ZoYQbgILkPSFpOEt7laxX1QIjSfcSQxwt6+IThfpXDukfhPWrgA+k9YVxRXRMy8HLY0pcztji4GouyKWQ4vvR9XrmpAcr5qz/uZZdJjcsmfBuu/m35RiygNEDpc8g6idw+RcJo2amd/jd0+5DY2KrO6BZszsVFhW4P5yu0ZDyPfRmhJA7zxjgcjyv007SsrlqsCkaerk8jwcZSACPxOLfEc5lwLekNiLTKjGzemQKZrk5igolo3ExDkuc7FtGvcly0LXp3ymaaXXI4lZYHXR2pPbVhBXvC0Pv+WgZAGNtAONhCkF/xqYlKICYPzRy41pBqiwHgjX0SryttvjQw+3m3yXA8ciWdHlSpZ2fsA8vQWRaliZVkHQEFtPhFML2u/sunIIQyK/F4grKaQeSSXmCBC91sshyWZJR8FfWsNELOtZPbGAXUxOx5CBcTnGjcTVU7XF+l2QDsaqTbDuJEuWmOkzp/EPm12INxVm5gglJPHJVEzLqKd3RGKeOB/u/oZeTMWjOz2fWTczELvPiTn05mKresm/fn8Ti8YVXy8n9jbhBuU1GEfISySlZj8HCWBr+yxgEsA4v9398hao6BcuvH77AxO71ZO25KAkFpJ90iS/DunuJjM=
  - secure: j8H2WSgnR1hcGB4OlRmMidYvCFUIatz7YfatMqlzPEXz+l9o6s17pQU28wRlGsTJZBmMpZQJM731xAo0jggKjBbJZiftiK1oGkppwPJ/8vDdR/mGbCpEbFmeN17DZe3aDr7jYotvBlRxtQSKAIjApAlXOU9AlnNe9N8nKVWO4AqyybDz9mBqNt56LoBwbN65o9WHmsNC3vNCeDbagBVE873KFYN7B/NVvZoo3SDa95UP7yLFIsfRCy2OpSFUr605nEw9K8u6w+asK3B+NGZCcLCF+ULpKMPdI1o1qVMDDbotezDavZt73xujvOjTnAChW3kZGJkTEpDkWQPBGEDh60xEl8vKnzHhfE5JNvJ7aiVfhhx3WUtsSea4NWFwVBTBLkgbGHIRRbnaTbARFesAxaPcW+nsnaLXt3QudbTkSWg6VrwIGxYfobUaDgodRLuu3+K3DZHh3/Q9XIMbfxOtGifNRjW7bdSedtX7t1n4Yp34EeklHz9YyN/alELCT8/gfTkj4XfpjDM72vLGSb19cIy6NqC7yfIesd/EbavcRqynYmguIs2MHRchZAB1HWz/i9fmMt6tcxYXZWh0Rz7oGwqfUCRLIfNOVN1tpleGnPKM4QuJ8L5aK0UWIpsN0B4i5d3PNa/bsfwwZZqls3eYNmgJ4nzGnUF0KrzCIP7pYs0=
