language: ruby
  # 2020-08-04: caching significantly reduces build time in travis,
  # but we're currently having issues with obtaining correct cached rvm
  # cache:
  #   bundler: true
  #   directories:
  #   - "/home/travis/.rvm/"
rvm:
- 2.5.7
before_install:
  # 2019-10-16: added to fix errors when upgrading rails env
  # 2020-08-04: removed to fix errors with travis deployment -- 
  # looks like travis internal rvm handling has changed
  # - rvm use 2.5.7 --install --binary --fuzzy
- gem --version
- gem install bundler -v '< 2'  # helps with compatibility issues when upgrading to rails 5
- bundle config --global github.https true
before_script:
- bundle exec rubocop
services:
- postgresql
script:
- bundle install
- psql -c "CREATE DATABASE mln_test;" -U postgres
# recreate test database from db/schema.rb
- bundle exec rake db:schema:load RAILS_ENV=test
# helps travis update its test db.  seems the schema load below doesn't always do it.
- bundle exec rake db:migrate RAILS_ENV=test
# - bundle exec rake db:test:prepare  # NOTE: might need this later.
# - bundle exec rake combined_tests:test
deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  bucket: 'my-library-nyc-config-development'
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-dev-1002
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: my-library-nyc-app-dev-1002
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: development
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  bucket: 'my-library-nyc-config-qa'
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-qa25
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-qa
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: qa
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-production
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: master
env:
  global:
  - secure: faZVumCAp4/e9vGo9whJZ1fZGFQ2qnfUxt4iQoMbXPlcBb2rVGia1hEiwrKpuJ/1mms7Rp7qhoZSR6rQQwjnGjQJ+cclAJo8X3yBpF33y7u/BwEQpS4XXxa1SNiIitYGIJ1bWxALQMkUgOoeI2D8LW7Pi1RKyW/CAWGD84bZocGT1S8VHX/zWl1JxtjZPGL2HmRuWXerIcQABA2xHaB9DZhEUNmF0jgwRdevDZQxJvAehpaB0I/meidFzd8k07O2DhgpCEHcf9SQzWf8MgGV9znnNRBjEESeZyKe8kSnSFk200mpENG9xAiJg/k88GaGTO6Biegj2RA5BFyOwpjxCn+E4eAN8AATMTy/rvoSssgBNAr0uqDmjkNcU6ffNuqPcbQEyhD1sb5XVPh0K2GcQ3yRzHqiVJpHreq5ESEtMLygUdPxHGMgYFpJBZ+udUGP6swUb4CDpEqVn/vmme8CtjKTSIsDIf3iS1nGxzd4TDtD8shqMOjdCgcz4rFuAr5Z9EPjTxbBUsPFkzOis60tuGPj9I1nyZ9+VDJhkJOzFhcS1LTXjRNTKfVNS1O7OVEIumu10eZLKOqgVp+SAGp+0wvHcRkX+74NvevTGUG3kwO+PQEm1YLdo5q5mcqmWbxggIwrTAHu/kjGEMLWUfTHbUjF+ZR7pptdCGUfLBQAJyM=
  - secure: bSAghtmg2DxfuS3vyCbD+bNQP3tyqc1VwooV5faInNx8DqbIdop81Z+J4m025F/AIyMrjnogm7boErW3JqbSfFYXHfGgedH9hYu2L5RLa2cn7QYD+KTDJaYIo9Z2GDExRtFOHsNJAf+IJ9gNGoRCRdNUyDAcKjJt4D+SIqB1PLMT9znc0wSPawIS1GrieZfj7zkid4hBH+xrRiE8I943+mQHvNCvkirKF/h7pEsMdcsGYATJIpKrT865k9oubLZvuzkgjOa3yMN02nxtnzMhHUiQpHgH5kXpvSiVAvbi84Ou9GEJY2sWdSwr0bezTICGjZagSPdsGuNC7oDYcJfwdLXk/CkF9o9VnXxn1KCki/5BSMK9LgrZ7epcMNEnZq8mpTZsCefc8jhF4V7Vd1Xw2b70Ei0Clfdn5cRfwcbVc9ytVLAzKUtFf3RJ6LlBJll0cBna3szEvrEQjiI3PdXwjtQLQOnj9tzV1J8RrmukKAY2W/ipG/44n9R7bhOx1MW6EgQFgKoYdGzdTP2CFLekEqNm4aibXCf4JBpW6QxVfp2sFfGduZVC8UUUJfdL6shIOrf6uQKhWehA90ZPBzlwO8j/A/DS7ISCsWRFKmt7itBWO+m86go/e2nz+mqs4a0r7WtXOSetKrJLChdc6kEKFd95towPIhmFdzxhUV+g7hA=
  - secure: mevQbvPCNL9bWtBC9F1T3ky0FXr7q1DOIcmngUJDyE0Onm2OEMj/LgF3ZpO9YPTL2OVT9B2yCfvfs2Mg3QKH5if5FIEoTwSUwU28cQmqgfwmdVvcUfGSxrhGZIxbKML1xV1U0HLnVrJMdusVHO1F8PhmXJ/vKAr0cDGZqcKx7sY5r7dG549McZUfbPmaqHampvGR/wFb+DacJxJ0xoNdLlvt/QKQPXfZIjFOKbA2hcqDc58XVJbd2xg6Xqhh7k5wmDDNVosod6qhL7OpXpQWZqVzVTLIZnwQk12caXd5RcvgdElToPAGikXgYktxmYEG3pUHm5Z53A43dvQUlIZt0Xp89zNZA7fQQ0Fh1MGFLpPRg2fln3h554c7RnKp2ZdO+herWT3wTUm2+C8xHKzM+3HOJEW1lEswT3uK9+qwlQ+fqYlH4ElYFD9KSmUpFHUksfE1eAJKhNbtJQTz04tOON2mtyxE2s7Q8kP7TEtXbjOnEg9fmpVt353WJCG13obS5AMqQX11oS2KSsWokJILbIcevKZPtnEeNYdpX+JfTGEH4lgKxsiSLBe3fyNw1ZXxwBaJXZyLFhAOrxQkBy7U/EQQiSt5nL90iRI/tC9teaiTi9hjvz9Ai9oCYWMAd/H9C3wztZqEv1l+pSOHWZ7RmsU80wjzXeSJOhFP9Xu4n+Q=