language: ruby
  # 2020-08-04: caching significantly reduces build time in travis,
  # but we're currently having issues with obtaining correct cached rvm
  # cache:
  #   bundler: true
  #   directories:
  #   - "/home/travis/.rvm/"
rvm:
- 2.7.4
before_install:
  # 2019-10-16: added to fix errors when upgrading rails env
  # 2020-08-04: removed to fix errors with travis deployment -- 
  # looks like travis internal rvm handling has changed
  # - rvm use 2.5.7 --install --binary --fuzzy
- gem --version
- gem install bundler -v '< 2'  # helps with compatibility issues when upgrading to rails 5
- bundle config --global github.https true
before_script:
# - bundle exec rubocop #for testing
services:
- postgresql
script:
- bundle install
- psql -c "CREATE DATABASE mln_test;" -U postgres

# For testing commeting below code
# recreate test database from db/schema.rb
# - bundle exec rake db:schema:load RAILS_ENV=test
# helps travis update its test db.  seems the schema load below doesn't always do it.
# - bundle exec rake db:migrate RAILS_ENV=test
# - bundle exec rake db:test:prepare  # NOTE: might need this later.
# - bundle exec rake combined_tests:test

# before_install:
# - nvm install '14.16.1'

# before_deploy:
# - bundle install
# - bundle exec rails webpacker:install
# - bundle exec rails webpacker:compile

deploy:
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_DEVELOPMENT"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_DEVELOPMENT"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-react-dev-18
  bucket_name: elasticbeanstalk-us-east-1-224280085904
  bucket_path: my-library-nyc-app-react-dev-18
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: development
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-qa25
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-qa25
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: qa-old
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_QA"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_QA"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-react-qa-27
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-react-qa-27
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: MLN-1104-rubocop-issues-latest1
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-production
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: master
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: "$AWS_ACCESS_KEY_ID_PRODUCTION"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY_PRODUCTION"
  region: us-east-1
  app: my-library-nyc-app
  env: my-library-nyc-app-react-production
  bucket_name: elasticbeanstalk-us-east-1-946183545209
  bucket_path: my-library-nyc-app-react-production
  on:
    repo: NYPL/MyLibraryNYCApp
    branch: production
env:
  global:
  - secure: VmSPZTuC7ZMDSloA+sxYBa5MP2rchrlSVLvMU7yuEv9HI8tw4FxzUmex1IBUG976zMdsfjerjjGiXaJURC2xQqWUqoFEG3wsvEKEKo9ydMAaWDN8fvlX3aEkKoG7YoBmUozsOEn+SbGiEFg8ApdB9OwDoZ+tVhNKs8TPD8KfJX3ho7ER2FpvfNPtb3l+ZydYWWyHx/jw0aW4DVrRxHFY6Z/ELyNjaLte6ikh9kRjwNQ/Krmss8aU+k5PrFi4U1JocQEgbKXhR+Vej2ASjpb9KIS/c/EWpvs8Z4uA3baYhrE7HsPLKtLnBelSsfqCRH7UOP+ZOWrgZOtvRQFjqCXoLzmKwBrlY9sNAYaPbTeEIUHpOUJgnHqWM2d0PuXqOV3aVxL1HiXDOqdcT7e2lgvBNgLRmdkXdTcYgZ5pTBF4W24n29sxpfzmKOalYVowiv2noqdeNAEbOWjd6Nj+UfYtwii6QRLRAGVx8qm38msoh1IsHNdjHIqYaAd4UYIU3nvN8veKUf42bUcrFafKG0TeMFs76ZUPBJQdlFgtBqDnEtRxhnhfc8NQxgbo1e+cdZapCMa579LDn+mNTuAiVLGxzUTssdCxvOQONZr/L7YKUl2RfJRbm1Hwa4aRUKHsb4tWTRbcqMXE8fnmA6nNjklHHzW5vCmJOF1enuGoLnfqQt8=
  - secure: ybrmOe2J5BJFW1BDY1OHAzAkvYfnDy3rKvg1bi/380NPlZjoyCNRct9bjeK1HtnG3p7A666EU9TG4NSxa71kzsx9g+w9WosjmgFEcUx863Ta9rcDJvdWM3GK5vFtMab+X3jo0qlzHApaK5GzNfR2+fm4IJ7YxcOlQwpPfxSx+08KAl+awzPjf5xacSI83h0BEjF4bD79YtK9mXRopoeF45Zw9t+2am5q1xXc0z1m/s4mIu0npFcgEy4o9wlQLA5/XGbBwi1EJqirlOwCVCA6zOpEv0HaLwmhZWmoHmzVnIo738c2eiIfZZMbZwX3+3NBtB1a6/VDLj+PZfI2X9wQMK6UNVN4QJDdhfKi/uGWWQ8D1jjUzRbX9vEUVxHConr5LT7+bAeJUcklUkin6nHxwpLnYh5Ezy/C3D85V/+X3lSlKPr2+4c+VjILzw0CurIW6Bl/0UN0FgvIOFG9O6Cw+Iai7+f/OmAf9xdvaF2TGTVkHGDTk3VdMeqpBDP/qso7EL2uvL9JVDIBcKKWH+vdKP6ApRkNNA86DNpDaxR171FoWjV3ugGTVYp5GH8ZhTZro96ZQbkWSrMcEfhcOLkHRnV9BIUjCYc72DRoaYItfuPhB0a5U3jthdRRJFgmhgJVoch1EYwEQkLWlTCKfNc7QW6vUE4lrTFAzEuvtc+334w=
