# frozen_string_literal: true

source 'https://rubygems.org'

gem 'delayed_job'
gem 'delayed_job_active_record'
gem 'daemons'

gem 'minitest-stub_any_instance'
gem 'rails'
gem 'actionpack'
gem 'actioncable'
gem 'activeadmin'
gem 'actionmailer'
gem 'activeadmin_reorderable'
gem 'activemodel'
gem 'activejob'
gem 'activerecord'
gem 'activestorage'
gem 'activesupport'
gem 'active_model_serializers'
gem 'acts_as_list'
gem 'addressable'
gem 'auto-session-timeout'
gem 'actionview'
gem 'aws-sdk'
gem 'client_side_validations'
gem 'cranky'
gem 'devise'
gem 'elasticsearch'
gem 'email_validator'
gem 'faker'
gem 'figaro'
gem 'font-awesome-rails'
gem 'railties'
gem 'google-api-client'
gem 'google_drive'
gem 'httparty'
gem 'json'
gem 'lograge'
#gem 'logstash-event', github: 'elastic/logstash', tag: 'v8.15.2'
gem 'nokogiri'
gem 'open_uri_redirections'
gem 'paper_trail'
gem 'pg'
gem 'rack-cors'
gem 'rails-controller-testing'
gem 'rubocop'
gem 'test-unit'
gem 'travis'
gem 'will_paginate'
gem 'webmock'
gem 'yaml_db'
gem 'rexml'
gem 'rubocop-performance'
gem 'thread_safe'
gem 'react_on_rails'
gem 'breakpoint'
gem 'execjs'
gem 'mini_racer'
gem 'bcrypt'
gem 'puma'
gem 'activeadmin_addons'
gem 'turbolinks'
gem 'rack'
gem 'jsonapi-serializer'
gem 'auto_increment'
gem 'luhn'
gem 'sprockets-rails'
gem 'turbo-rails'
gem 'stimulus-rails'
gem 'jsbundling-rails'
gem 'cssbundling-rails'
gem 'jquery-rails'
gem 'importmap-rails'

group :assets do # Gems used only for assets and not required in production environments by default.
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

group :development do
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-remote'
  gem 'pry-nav'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
end

group :test do
  gem 'minitest'
  gem 'simplecov'
  gem 'database_cleaner'
  gem 'rspec-rails'
end
