# frozen_string_literal: true

source 'https://rubygems.org'

gem 'delayed_job', '~> 4.1'
gem 'delayed_job_active_record', '~> 4.1'
gem 'daemons', '~> 1.4'

gem 'minitest-stub_any_instance', '~> 1.0'
gem 'rails', '~> 7.2'
gem 'actionpack', '~> 7.2'
gem 'actioncable', '~> 7.2'
gem 'activeadmin', '~> 3.2'
gem 'actionmailer', '~> 7.2'
gem 'activeadmin_reorderable', '~> 0.3'
gem 'activemodel', '~> 7.2'
gem 'activejob', '~> 7.2'
gem 'activerecord', '~> 7.2'
gem 'activestorage', '~> 7.2'
gem 'activesupport', '~> 7.2'
gem 'active_model_serializers', '~> 0.10'
gem 'acts_as_list', '~> 1.2'
gem 'addressable', '~> 2.8'
gem 'auto-session-timeout', '~> 1.2'
gem 'actionview', '~> 7.2'
gem 'aws-sdk', '~> 3.2'
gem 'client_side_validations', '~> 22.2'
gem 'cranky', '~> 1.1'
gem 'devise', '~> 4.9'
gem 'elasticsearch', '6.8'
gem 'email_validator', '~> 2.2'
gem 'faker', '~> 3.4'
gem 'figaro', '~> 1.2'
gem 'font-awesome-rails', '~> 4.7'
gem 'railties', '~> 7.2'
gem 'google-api-client', '~> 0.53'
gem 'google_drive', '~> 3.0'
gem 'httparty', '~> 0.22'
gem 'json', '~> 2.7'
gem 'lograge', '~> 0.14'
gem 'mutex_m', '~> 0.2'
gem 'nokogiri', '~> 1.16'
gem 'open_uri_redirections', '~> 0.2'
gem 'ostruct', '~> 0.6'
gem 'paper_trail', '~> 15.2'
gem 'pg', '~> 1.5'
gem 'rack-cors', '~> 2.0'
gem 'rails-controller-testing', '~> 1.0'
gem 'rubocop', '~> 1.66'
gem 'test-unit', '~> 3.6'
gem 'travis', '~> 1.8'
gem 'will_paginate', '~> 4.0'
gem 'webmock', '~> 3.24'
gem 'yaml_db', '~> 0.7'
gem 'rexml', '~> 3.3'
gem 'rubocop-performance', '~> 1.22'
gem 'thread_safe', '~> 0.3'
gem 'react_on_rails', '~> 14.0'
gem 'breakpoint', '~> 2.7'
gem 'execjs', '~> 2.9'
gem 'mini_racer', '~> 0.16'
gem 'bcrypt', '~> 3.1'
gem 'puma', '~> 6.4'
gem 'activeadmin_addons', '~> 1.10'
gem 'turbolinks', '~> 5.2'
gem 'rack', '~> 3.1'
gem 'jsonapi-serializer', '~> 2.2'
gem 'auto_increment', '~> 1.6'
gem 'luhn', '~> 1.0'
gem 'sprockets-rails', '~> 3.5'
gem 'turbo-rails', '~> 2.0'
gem 'stimulus-rails', '~> 1.3'
gem 'jsbundling-rails', '~> 1.3'
gem 'cssbundling-rails', '~> 1.4'
gem 'jquery-rails', '~> 4.6'
gem 'importmap-rails', '~> 2.0'

group :assets do # Gems used only for assets and not required in production environments by default.
  gem 'sass-rails', '~> 6.0'
  gem 'coffee-rails', '~> 5.0'
  gem 'uglifier', '~> 4.2'
end

group :development do
  gem 'pry', '~> 0.14'
  gem 'pry-rails', '~> 0.3'
  gem 'pry-remote', '~> 0.1'
  gem 'pry-nav', '~> 1.0'
  gem 'pry-rescue', '~> 1.6'
  gem 'pry-stack_explorer', '~> 0.6'
end

group :test do
  gem 'factory_bot_rails', '~> 6.4'
  gem 'minitest', '~> 5.25'
  gem 'minitest-reporters', '~> 1.7'
  gem 'mocha', '~> 2.4'
  gem 'simplecov', '~> 0.22'
  gem 'database_cleaner', '~> 2.0'
  gem 'rails-perftest', '~> 0.0'
  gem 'rspec-rails', '~> 7.0'
  gem 'spring', '~> 4.2'
  gem 'spring-commands-rspec', '~> 1.0'
end
