local:
  teachersets:
    host: 'http://localhost:9200/'
    connect_timeout: 3
    index: 'teacherset'
    type: 'teacherset'
    size: 20

development:
  teachersets:
    host: 'https://vpc-mylibrarynyc-development-yvrqkaicwhwb5tiz3n365a3xza.us-east-1.es.amazonaws.com/'
    connect_timeout: 3
    index: 'teacherset'
    type: 'teacherset'
    size: 20

qa:
  teachersets:
    host: 'TODO'
    connect_timeout: 3
    index: 'teacherset'
    type: 'teacherset'
    size: 20

prod:
  teachersets:
    host: 'TODO'
    connect_timeout: 3
    index: 'teacherset'
    type: 'teacherset'
    size: 20

test:
  teachersets:
    host: 'https://vpc-mylibrarynyc-development-yvrqkaicwhwb5tiz3n365a3xza.us-east-1.es.amazonaws.com/'
    connect_timeout: 3
    index: 'teacherset'
    type: 'teacherset'
    size: 20
