local:
  teacherset.data.from.elasticsearch.enabled: true
  news_letter.enabled: true
development:
  teacherset.data.from.elasticsearch.enabled: true
  news_letter.enabled: true
qa:
  teacherset.data.from.elasticsearch.enabled: true
  news_letter.enabled: true
production:
  teacherset.data.from.elasticsearch.enabled: false
  news_letter.enabled: false
test:
  teacherset.data.from.elasticsearch.enabled: true
  news_letter.enabled: true