local:
  teacherset.data.from.elasticsearch.enabled: true

development:
  teacherset.data.from.elasticsearch.enabled: true

qa:
  teacherset.data.from.elasticsearch.enabled: true

production:
  teacherset.data.from.elasticsearch.enabled: true

test:
  teacherset.data.from.elasticsearch.enabled: true