local:
  teacherset.data.from.elasticsearch.enabled: true

development:
  teacherset.data.from.elasticsearch.enabled: true

qa:
  teacherset.data.from.elasticsearch.enabled: false

prod:
  teacherset.data.from.elasticsearch.enabled: false

test:
  teacherset.data.from.elasticsearch.enabled: true