name: CI

on:
  push:
    branches:
      - TGR-130-unit-tests-run-automatically

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2

      - name: set up docker
        uses: docker/setup-buildx-action@v2

      - name: install docker compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: build application
        run: |
          docker-compose build

      - name: Run tests
        run: |
          docker-compose up -d
          docker-compose exec webapp bundle exec rails test
